#! /usr/bin/bash

# extract raw count for Nrf2 15 CpG sites
# R Wu. Oct 2018
# Usage:  bash extract_nrf2_15_CpG.sh combined.csv
# replaced combined.csv with the file generated by combined_CpG.py -- a script from the DMRfinder tool set.
# A file named Nrf2_15_CpG.csv will be generated after execution of this script.

# single CpG for Nrf2, the 15 CpGs. Note CpG 1-5 are not coverd by the SureSelect Kit.
# chr	start		dist. 	CpG
# chr2	75705582	-287	1
# chr2	75705564	-269	2
# chr2	75705554	-259	3
# chr2	75705551	-256	4
# chr2	75705540	-245	5
# chr2	75705467	-172	6
# chr2	75705431	-136	7
# chr2	75705407	-112	8
# chr2	75705366	-71	9
# chr2	75705355	-60	10
# chr2	75705342	-47	11
# chr2	75705320	-25	12
# chr2	75705312	-17	13
# chr2	75705306	-11	14
# chr2	75705295	0	15

# The range for Nrf2 is chr2 75705295 - 75705582
# 75705:
# 295 - 299
# 300 - 499
# 500 - 579
# 580 - 582

# Regexp is  75705(29[5-9]|[3-4][0-9][0-9]|5[0-7][0-9]|58[0-2])

# CMD is grep -P "chr2\t75705(29[5-9]|[3-4][0-9][0-9]|5[0-7][0-9]|58[0-2])" file.csv


head -1 $1 > Nrf2_15_CpG.csv
grep -P "chr2\t75705(29[5-9]|[3-4][0-9][0-9]|5[0-7][0-9]|58[0-2])" $1 >> Nrf2_15_CpG.csv

